[2025-03-11T10:43:23.583+0000] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: csv_etl_pipeline.extract_task manual__2025-03-11T10:43:21.071268+00:00 [queued]>
[2025-03-11T10:43:23.593+0000] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: csv_etl_pipeline.extract_task manual__2025-03-11T10:43:21.071268+00:00 [queued]>
[2025-03-11T10:43:23.593+0000] {taskinstance.py:1308} INFO - Starting attempt 1 of 1
[2025-03-11T10:43:23.608+0000] {taskinstance.py:1327} INFO - Executing <Task(PythonOperator): extract_task> on 2025-03-11 10:43:21.071268+00:00
[2025-03-11T10:43:23.616+0000] {standard_task_runner.py:57} INFO - Started process 790 to run task
[2025-03-11T10:43:23.620+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'csv_etl_pipeline', 'extract_task', 'manual__2025-03-11T10:43:21.071268+00:00', '--job-id', '11', '--raw', '--subdir', 'DAGS_FOLDER/etl.py', '--cfg-path', '/tmp/tmpemsoqi5i']
[2025-03-11T10:43:23.621+0000] {standard_task_runner.py:85} INFO - Job 11: Subtask extract_task
[2025-03-11T10:43:23.680+0000] {task_command.py:410} INFO - Running <TaskInstance: csv_etl_pipeline.extract_task manual__2025-03-11T10:43:21.071268+00:00 [running]> on host 11da0919092a
[2025-03-11T10:43:23.768+0000] {taskinstance.py:1547} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='csv_etl_pipeline' AIRFLOW_CTX_TASK_ID='extract_task' AIRFLOW_CTX_EXECUTION_DATE='2025-03-11T10:43:21.071268+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-03-11T10:43:21.071268+00:00'
[2025-03-11T10:43:23.771+0000] {logging_mixin.py:149} INFO - dags
[2025-03-11T10:43:23.771+0000] {logging_mixin.py:149} INFO - logs
[2025-03-11T10:43:23.771+0000] {logging_mixin.py:149} INFO - ***-worker.pid
[2025-03-11T10:43:23.771+0000] {logging_mixin.py:149} INFO - webserver_config.py
[2025-03-11T10:43:23.772+0000] {logging_mixin.py:149} INFO - ***.cfg
[2025-03-11T10:43:23.772+0000] {logging_mixin.py:149} INFO - config
[2025-03-11T10:43:23.772+0000] {logging_mixin.py:149} INFO - plugins
[2025-03-11T10:43:23.797+0000] {taskinstance.py:1824} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 181, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 198, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/etl.py", line 21, in extract_data
    df = pd.read_csv(INPUT_CSV)
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/util/_decorators.py", line 311, in wrapper
    return func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/parsers/readers.py", line 586, in read_csv
    return _read(filepath_or_buffer, kwds)
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/parsers/readers.py", line 488, in _read
    return parser.read(nrows)
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/parsers/readers.py", line 1047, in read
    index, columns, col_dict = self._engine.read(nrows)
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/parsers/c_parser_wrapper.py", line 224, in read
    chunks = self._reader.read_low_memory(nrows)
  File "pandas/_libs/parsers.pyx", line 801, in pandas._libs.parsers.TextReader.read_low_memory
  File "pandas/_libs/parsers.pyx", line 857, in pandas._libs.parsers.TextReader._read_rows
  File "pandas/_libs/parsers.pyx", line 843, in pandas._libs.parsers.TextReader._tokenize_rows
  File "pandas/_libs/parsers.pyx", line 1925, in pandas._libs.parsers.raise_parser_error
pandas.errors.ParserError: Error tokenizing data. C error: Expected 1 fields in line 257, saw 2

[2025-03-11T10:43:23.811+0000] {taskinstance.py:1350} INFO - Marking task as FAILED. dag_id=csv_etl_pipeline, task_id=extract_task, execution_date=20250311T104321, start_date=20250311T104323, end_date=20250311T104323
[2025-03-11T10:43:23.826+0000] {standard_task_runner.py:109} ERROR - Failed to execute job 11 for task extract_task (Error tokenizing data. C error: Expected 1 fields in line 257, saw 2
; 790)
[2025-03-11T10:43:23.872+0000] {local_task_job_runner.py:225} INFO - Task exited with return code 1
[2025-03-11T10:43:23.902+0000] {taskinstance.py:2651} INFO - 0 downstream tasks scheduled from follow-on schedule check
