[2025-03-11T10:38:55.649+0000] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: csv_etl_pipeline.extract_task manual__2025-03-11T10:38:53.244550+00:00 [queued]>
[2025-03-11T10:38:55.663+0000] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: csv_etl_pipeline.extract_task manual__2025-03-11T10:38:53.244550+00:00 [queued]>
[2025-03-11T10:38:55.663+0000] {taskinstance.py:1308} INFO - Starting attempt 1 of 1
[2025-03-11T10:38:55.684+0000] {taskinstance.py:1327} INFO - Executing <Task(PythonOperator): extract_task> on 2025-03-11 10:38:53.244550+00:00
[2025-03-11T10:38:55.693+0000] {standard_task_runner.py:57} INFO - Started process 712 to run task
[2025-03-11T10:38:55.699+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'csv_etl_pipeline', 'extract_task', 'manual__2025-03-11T10:38:53.244550+00:00', '--job-id', '9', '--raw', '--subdir', 'DAGS_FOLDER/etl.py', '--cfg-path', '/tmp/tmpyasn2602']
[2025-03-11T10:38:55.700+0000] {standard_task_runner.py:85} INFO - Job 9: Subtask extract_task
[2025-03-11T10:38:55.794+0000] {task_command.py:410} INFO - Running <TaskInstance: csv_etl_pipeline.extract_task manual__2025-03-11T10:38:53.244550+00:00 [running]> on host 11da0919092a
[2025-03-11T10:38:55.915+0000] {taskinstance.py:1547} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='csv_etl_pipeline' AIRFLOW_CTX_TASK_ID='extract_task' AIRFLOW_CTX_EXECUTION_DATE='2025-03-11T10:38:53.244550+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-03-11T10:38:53.244550+00:00'
[2025-03-11T10:38:55.922+0000] {logging_mixin.py:149} INFO - dags
[2025-03-11T10:38:55.922+0000] {logging_mixin.py:149} INFO - logs
[2025-03-11T10:38:55.922+0000] {logging_mixin.py:149} INFO - ***-worker.pid
[2025-03-11T10:38:55.922+0000] {logging_mixin.py:149} INFO - webserver_config.py
[2025-03-11T10:38:55.922+0000] {logging_mixin.py:149} INFO - ***.cfg
[2025-03-11T10:38:55.922+0000] {logging_mixin.py:149} INFO - config
[2025-03-11T10:38:55.922+0000] {logging_mixin.py:149} INFO - plugins
[2025-03-11T10:38:55.928+0000] {taskinstance.py:1824} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 181, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 198, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/etl.py", line 21, in extract_data
    df = pd.read_csv(INPUT_CSV)
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/util/_decorators.py", line 311, in wrapper
    return func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/parsers/readers.py", line 586, in read_csv
    return _read(filepath_or_buffer, kwds)
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/parsers/readers.py", line 482, in _read
    parser = TextFileReader(filepath_or_buffer, **kwds)
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/parsers/readers.py", line 811, in __init__
    self._engine = self._make_engine(self.engine)
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/parsers/readers.py", line 1040, in _make_engine
    return mapping[engine](self.f, **self.options)  # type: ignore[call-arg]
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/parsers/c_parser_wrapper.py", line 51, in __init__
    self._open_handles(src, kwds)
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/parsers/base_parser.py", line 229, in _open_handles
    errors=kwds.get("encoding_errors", "strict"),
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/common.py", line 707, in get_handle
    newline="",
FileNotFoundError: [Errno 2] No such file or directory: 'Vente.csv'
[2025-03-11T10:38:55.940+0000] {taskinstance.py:1350} INFO - Marking task as FAILED. dag_id=csv_etl_pipeline, task_id=extract_task, execution_date=20250311T103853, start_date=20250311T103855, end_date=20250311T103855
[2025-03-11T10:38:55.955+0000] {standard_task_runner.py:109} ERROR - Failed to execute job 9 for task extract_task ([Errno 2] No such file or directory: 'Vente.csv'; 712)
[2025-03-11T10:38:55.991+0000] {local_task_job_runner.py:225} INFO - Task exited with return code 1
[2025-03-11T10:38:56.025+0000] {taskinstance.py:2651} INFO - 0 downstream tasks scheduled from follow-on schedule check
