[2025-03-11T15:20:15.756+0000] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: file_watcher_dag.wait_for_new_file scheduled__2025-03-11T15:19:44.613291+00:00 [queued]>
[2025-03-11T15:20:15.765+0000] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: file_watcher_dag.wait_for_new_file scheduled__2025-03-11T15:19:44.613291+00:00 [queued]>
[2025-03-11T15:20:15.765+0000] {taskinstance.py:1308} INFO - Starting attempt 1 of 1
[2025-03-11T15:20:15.779+0000] {taskinstance.py:1327} INFO - Executing <Task(FileSensor): wait_for_new_file> on 2025-03-11 15:19:44.613291+00:00
[2025-03-11T15:20:15.786+0000] {standard_task_runner.py:57} INFO - Started process 999 to run task
[2025-03-11T15:20:15.790+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'file_watcher_dag', 'wait_for_new_file', 'scheduled__2025-03-11T15:19:44.613291+00:00', '--job-id', '308', '--raw', '--subdir', 'DAGS_FOLDER/watch.py', '--cfg-path', '/tmp/tmpshn7pt66']
[2025-03-11T15:20:15.793+0000] {standard_task_runner.py:85} INFO - Job 308: Subtask wait_for_new_file
[2025-03-11T15:20:15.839+0000] {task_command.py:410} INFO - Running <TaskInstance: file_watcher_dag.wait_for_new_file scheduled__2025-03-11T15:19:44.613291+00:00 [running]> on host 72a7cd2d8042
[2025-03-11T15:20:15.936+0000] {taskinstance.py:1547} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='file_watcher_dag' AIRFLOW_CTX_TASK_ID='wait_for_new_file' AIRFLOW_CTX_EXECUTION_DATE='2025-03-11T15:19:44.613291+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-03-11T15:19:44.613291+00:00'
[2025-03-11T15:20:15.947+0000] {base.py:73} INFO - Using connection ID 'fs_default' for task execution.
[2025-03-11T15:20:15.947+0000] {filesystem.py:64} INFO - Poking for file /opt/***/dags/data/Vente.csv
[2025-03-11T15:20:25.965+0000] {base.py:73} INFO - Using connection ID 'fs_default' for task execution.
[2025-03-11T15:20:25.965+0000] {filesystem.py:64} INFO - Poking for file /opt/***/dags/data/Vente.csv
[2025-03-11T15:20:35.982+0000] {base.py:73} INFO - Using connection ID 'fs_default' for task execution.
[2025-03-11T15:20:35.982+0000] {filesystem.py:64} INFO - Poking for file /opt/***/dags/data/Vente.csv
[2025-03-11T15:20:35.983+0000] {taskinstance.py:1824} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/sensors/base.py", line 242, in execute
    raise AirflowSensorTimeout(message)
airflow.exceptions.AirflowSensorTimeout: Sensor has timed out; run duration of 20.044836376000603 seconds exceeds the specified timeout of 20.
[2025-03-11T15:20:35.990+0000] {taskinstance.py:1350} INFO - Immediate failure requested. Marking task as FAILED. dag_id=file_watcher_dag, task_id=wait_for_new_file, execution_date=20250311T151944, start_date=20250311T152015, end_date=20250311T152035
[2025-03-11T15:20:36.001+0000] {standard_task_runner.py:109} ERROR - Failed to execute job 308 for task wait_for_new_file (Sensor has timed out; run duration of 20.044836376000603 seconds exceeds the specified timeout of 20.; 999)
[2025-03-11T15:20:36.010+0000] {local_task_job_runner.py:225} INFO - Task exited with return code 1
[2025-03-11T15:20:36.036+0000] {taskinstance.py:2651} INFO - 0 downstream tasks scheduled from follow-on schedule check
